defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  pool: 5
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  username: root
  pool: 5
  host: localhost
  database: Booka
  password: db4root
  reconnect: false

production:
  database: Booka
  username: root
  password: db4root


test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
