defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  pool: 5
  host: localhost

development:
  database: Booka
  password:
  reconnect: false
  <<: *defaults

staging:
  database: Booka
  password:
  reconnect: false
  <<: *defaults


production:
  database: Booka
  password: db4root
  <<: *defaults


test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
